#!/bin/bash
mkdir -p squished
for filename in $@; do
	mynewname=${filename%.*}"sm.unc"
	squishunc $filename "squished/"$mynewname
	oldstats=$(unimax $filename)
	newstats=$(unimax "squished/"$mynewname)
	#printf "%s %s\n" $oldstats $newstats
	echo  $oldstats " | "  $newstats
done
rm tmp.unc
rm tmp2.unc

